# install pre-commit git hooks
# pre-commit install
#
# pre-commit run --all-files
ci:
  autofix_prs: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: sort-simple-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: mix-format
      - id: mix-test
