defmodule Poc.Repo.Migrations.AddAccountResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :type, :text, null: false
      add :minutes, :bigint, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "accounts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :visit_id,
          references(:visits,
            column: :id,
            name: "accounts_visit_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:accounts, "accounts_visit_id_fkey")

    drop constraint(:accounts, "accounts_user_id_fkey")

    drop table(:accounts)
  end
end
