defmodule Poc.Repo.Migrations.AddVisitResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:visits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :task, :text, null: false
      add :minutes, :bigint, null: false

      add :member_id,
          references(:users,
            column: :id,
            name: "visits_member_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :pal_id,
          references(:users,
            column: :id,
            name: "visits_pal_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:visits, "visits_pal_id_fkey")

    drop constraint(:visits, "visits_member_id_fkey")

    drop table(:visits)
  end
end
